### ISSUE TITLE
 Hide personal information

### ISSUE THREAD

**Issue by EthanReedLabs** [Blankj/resume#2]
I suggest you hide your personal information.

**Comment by Blankj** [comment]
Thank you for your suggestion.

**Comment by EthanReedLabs** [comment]
国内盗用信息的人太多了，手机号和名字很重要的。泄露了，会有很多人烦你。

布兰柯基 <notifications@github.com> 于2018年9月29日周六 下午2:27写道：

**Comment by Blankj** [comment]
已经删除过去提交的信息了，感谢哈
